modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "soul_shard"
version = "${version}"
displayName = "Soul Shard"
authors = "Konoplanyy"
description = '''
 Soul Shard — A Vanilla+ death utility that neatly contains your dropped items in a breakable crystal, keeping your loot organized while preserving the classic 5-minute risk.
'''
#logoFile = ""

[[dependencies.soul_shard]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soul_shard]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soul_shard]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "soul_shard.mixins.json"
