["Soul Shard Settings"]
	#Crystal lifetime in seconds (-1 = infinite)
	# Default: 300
	# Range: > -1
	crystalLifeTime = 300
	#Can die
	canDie = true
	#Do items drop when a crystal is destroyed
	dropItemsOnBreak = true
	#amount of health in the crystal
	# Default: 10
	# Range: > 1
	crystalHealth = 10
